services:
  protoc-builder:
    build:
      context: .
      dockerfile: internal/github_cel/interfaces/Dockerfile
    volumes:
      - .:/workspace
    command: /bin/bash -c "protoc --proto_path=/workspace/internal/github_cel/interfaces --go_out=. --go-grpc_out=. /workspace/internal/github_cel/interfaces/access_information.proto"
    
    working_dir: /workspace
    environment:
      - GOPATH=/go
