// Code generated by protoc-gen-go-grpc. DO NOT EDIT.
// versions:
// - protoc-gen-go-grpc v1.5.1
// - protoc             v3.21.12
// source: access_information.proto

package interfaces

import (
	context "context"
	grpc "google.golang.org/grpc"
	codes "google.golang.org/grpc/codes"
	status "google.golang.org/grpc/status"
)

// This is a compile-time assertion to ensure that this generated file
// is compatible with the grpc package it is being compiled against.
// Requires gRPC-Go v1.64.0 or later.
const _ = grpc.SupportPackageIsVersion9

const (
	GitAccessInformationV1_GetAccessInformation_FullMethodName = "/git_access_information.GitAccessInformationV1/GetAccessInformation"
)

// GitAccessInformationV1Client is the client API for GitAccessInformationV1 service.
//
// For semantics around ctx use and closing/ending streaming RPCs, please refer to https://pkg.go.dev/google.golang.org/grpc/?tab=doc#ClientConn.NewStream.
type GitAccessInformationV1Client interface {
	GetAccessInformation(ctx context.Context, in *AccessInformationRequest, opts ...grpc.CallOption) (*AccessInformationResponse, error)
}

type gitAccessInformationV1Client struct {
	cc grpc.ClientConnInterface
}

func NewGitAccessInformationV1Client(cc grpc.ClientConnInterface) GitAccessInformationV1Client {
	return &gitAccessInformationV1Client{cc}
}

func (c *gitAccessInformationV1Client) GetAccessInformation(ctx context.Context, in *AccessInformationRequest, opts ...grpc.CallOption) (*AccessInformationResponse, error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	out := new(AccessInformationResponse)
	err := c.cc.Invoke(ctx, GitAccessInformationV1_GetAccessInformation_FullMethodName, in, out, cOpts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

// GitAccessInformationV1Server is the server API for GitAccessInformationV1 service.
// All implementations must embed UnimplementedGitAccessInformationV1Server
// for forward compatibility.
type GitAccessInformationV1Server interface {
	GetAccessInformation(context.Context, *AccessInformationRequest) (*AccessInformationResponse, error)
	mustEmbedUnimplementedGitAccessInformationV1Server()
}

// UnimplementedGitAccessInformationV1Server must be embedded to have
// forward compatible implementations.
//
// NOTE: this should be embedded by value instead of pointer to avoid a nil
// pointer dereference when methods are called.
type UnimplementedGitAccessInformationV1Server struct{}

func (UnimplementedGitAccessInformationV1Server) GetAccessInformation(context.Context, *AccessInformationRequest) (*AccessInformationResponse, error) {
	return nil, status.Errorf(codes.Unimplemented, "method GetAccessInformation not implemented")
}
func (UnimplementedGitAccessInformationV1Server) mustEmbedUnimplementedGitAccessInformationV1Server() {
}
func (UnimplementedGitAccessInformationV1Server) testEmbeddedByValue() {}

// UnsafeGitAccessInformationV1Server may be embedded to opt out of forward compatibility for this service.
// Use of this interface is not recommended, as added methods to GitAccessInformationV1Server will
// result in compilation errors.
type UnsafeGitAccessInformationV1Server interface {
	mustEmbedUnimplementedGitAccessInformationV1Server()
}

func RegisterGitAccessInformationV1Server(s grpc.ServiceRegistrar, srv GitAccessInformationV1Server) {
	// If the following call pancis, it indicates UnimplementedGitAccessInformationV1Server was
	// embedded by pointer and is nil.  This will cause panics if an
	// unimplemented method is ever invoked, so we test this at initialization
	// time to prevent it from happening at runtime later due to I/O.
	if t, ok := srv.(interface{ testEmbeddedByValue() }); ok {
		t.testEmbeddedByValue()
	}
	s.RegisterService(&GitAccessInformationV1_ServiceDesc, srv)
}

func _GitAccessInformationV1_GetAccessInformation_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(AccessInformationRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(GitAccessInformationV1Server).GetAccessInformation(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: GitAccessInformationV1_GetAccessInformation_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(GitAccessInformationV1Server).GetAccessInformation(ctx, req.(*AccessInformationRequest))
	}
	return interceptor(ctx, in, info, handler)
}

// GitAccessInformationV1_ServiceDesc is the grpc.ServiceDesc for GitAccessInformationV1 service.
// It's only intended for direct use with grpc.RegisterService,
// and not to be introspected or modified (even as a copy)
var GitAccessInformationV1_ServiceDesc = grpc.ServiceDesc{
	ServiceName: "git_access_information.GitAccessInformationV1",
	HandlerType: (*GitAccessInformationV1Server)(nil),
	Methods: []grpc.MethodDesc{
		{
			MethodName: "GetAccessInformation",
			Handler:    _GitAccessInformationV1_GetAccessInformation_Handler,
		},
	},
	Streams:  []grpc.StreamDesc{},
	Metadata: "access_information.proto",
}
